{'915339293048082432': {'_id': ObjectId('59e0cbbe3842ed08188235f7'),
                        'contributors': None,
                        'coordinates': None,
                        'created_at': 'Tue Oct 03 22:14:28 +0000 2017',
                        'entities': {'hashtags': [{'indices': [95, 103],
                                                   'text': 'machine'},
                                                  {'indices': [104, 113],
                                                   'text': 'learning'},
                                                  {'indices': [114, 121],
                                                   'text': 'python'}],
                                     'symbols': [],
                                     'urls': [{'display_url': 'zpy.io/a3fc66fb',
                                               'expanded_url': 'http://zpy.io/a3fc66fb',
                                               'indices': [71, 94],
                                               'url': 'https://t.co/GHzON6itMG'}],
                                     'user_mentions': [{'id': 726709023563747328,
                                                        'id_str': '726709023563747328',
                                                        'indices': [122, 133],
                                                        'name': 'Python Bot',
                                                        'screen_name': 'pythonbot_'}]},
                        'favorite_count': 2,
                        'favorited': False,
                        'geo': None,
                        'id': 915339293048082432,
                        'id_str': '915339293048082432',
                        'in_reply_to_screen_name': None,
                        'in_reply_to_status_id': None,
                        'in_reply_to_status_id_str': None,
                        'in_reply_to_user_id': None,
                        'in_reply_to_user_id_str': None,
                        'is_quote_status': False,
                        'lang': 'es',
                        'metadata': {'iso_language_code': 'es',
                                     'result_type': 'recent'},
                        'place': None,
                        'possibly_sensitive': False,
                        'retweet_count': 0,
                        'retweeted': False,
                        'source': '<a href="https://twitter.com/pythonbot_" '
                                  'rel="nofollow">Python Bot2</a>',
                        'text': 'Python Para Informaticos: Explorando La '
                                'Informacion (spanish Edition)  '
                                'https://t.co/GHzON6itMG #machine #learning '
                                '#python @pythonbot_',
                        'truncated': False,
                        'user': {'contributors_enabled': False,
                                 'created_at': 'Sun May 01 09:45:07 +0000 2016',
                                 'default_profile': False,
                                 'default_profile_image': False,
                                 'description': 'I retweet everything about '
                                                '#Python programming language '
                                                '!',
                                 'entities': {'description': {'urls': []}},
                                 'favourites_count': 0,
                                 'follow_request_sent': False,
                                 'followers_count': 2762,
                                 'following': False,
                                 'friends_count': 2871,
                                 'geo_enabled': False,
                                 'has_extended_profile': False,
                                 'id': 726709023563747328,
                                 'id_str': '726709023563747328',
                                 'is_translation_enabled': False,
                                 'is_translator': False,
                                 'lang': 'en',
                                 'listed_count': 382,
                                 'location': '',
                                 'name': 'Python Bot',
                                 'notifications': False,
                                 'profile_background_color': '000000',
                                 'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
                                 'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
                                 'profile_background_tile': False,
                                 'profile_banner_url': 'https://pbs.twimg.com/profile_banners/726709023563747328/1504969738',
                                 'profile_image_url': 'http://pbs.twimg.com/profile_images/726714034066706433/5NWdOzpJ_normal.jpg',
                                 'profile_image_url_https': 'https://pbs.twimg.com/profile_images/726714034066706433/5NWdOzpJ_normal.jpg',
                                 'profile_link_color': '1B95E0',
                                 'profile_sidebar_border_color': '000000',
                                 'profile_sidebar_fill_color': '000000',
                                 'profile_text_color': '000000',
                                 'profile_use_background_image': False,
                                 'protected': False,
                                 'screen_name': 'pythonbot_',
                                 'statuses_count': 51771,
                                 'time_zone': 'Pacific Time (US & Canada)',
                                 'translator_type': 'none',
                                 'url': None,
                                 'utc_offset': -25200,
                                 'verified': False}},
 '915892147106320384': {'_id': ObjectId('59e0cbbb3842ed081882356f'),
                        'contributors': None,
                        'coordinates': None,
                        'created_at': 'Thu Oct 05 10:51:18 +0000 2017',
                        'entities': {'hashtags': [{'indices': [95, 103],
                                                   'text': 'machine'},
                                                  {'indices': [104, 113],
                                                   'text': 'learning'},
                                                  {'indices': [114, 121],
                                                   'text': 'python'}],
                                     'symbols': [],
                                     'urls': [{'display_url': 'zpy.io/a3fc66fb',
                                               'expanded_url': 'http://zpy.io/a3fc66fb',
                                               'indices': [71, 94],
                                               'url': 'https://t.co/GHzON6itMG'}],
                                     'user_mentions': [{'id': 726709023563747328,
                                                        'id_str': '726709023563747328',
                                                        'indices': [122, 133],
                                                        'name': 'Python Bot',
                                                        'screen_name': 'pythonbot_'}]},
                        'favorite_count': 0,
                        'favorited': False,
                        'geo': None,
                        'id': 915892147106320384,
                        'id_str': '915892147106320384',
                        'in_reply_to_screen_name': None,
                        'in_reply_to_status_id': None,
                        'in_reply_to_status_id_str': None,
                        'in_reply_to_user_id': None,
                        'in_reply_to_user_id_str': None,
                        'is_quote_status': False,
                        'lang': 'es',
                        'metadata': {'iso_language_code': 'es',
                                     'result_type': 'recent'},
                        'place': None,
                        'possibly_sensitive': False,
                        'retweet_count': 0,
                        'retweeted': False,
                        'source': '<a href="https://twitter.com/pythonbot_" '
                                  'rel="nofollow">Python Bot2</a>',
                        'text': 'Python Para Informaticos: Explorando La '
                                'Informacion (spanish Edition)  '
                                'https://t.co/GHzON6itMG #machine #learning '
                                '#python @pythonbot_',
                        'truncated': False,
                        'user': {'contributors_enabled': False,
                                 'created_at': 'Sun May 01 09:45:07 +0000 2016',
                                 'default_profile': False,
                                 'default_profile_image': False,
                                 'description': 'I retweet everything about '
                                                '#Python programming language '
                                                '!',
                                 'entities': {'description': {'urls': []}},
                                 'favourites_count': 0,
                                 'follow_request_sent': False,
                                 'followers_count': 2762,
                                 'following': False,
                                 'friends_count': 2871,
                                 'geo_enabled': False,
                                 'has_extended_profile': False,
                                 'id': 726709023563747328,
                                 'id_str': '726709023563747328',
                                 'is_translation_enabled': False,
                                 'is_translator': False,
                                 'lang': 'en',
                                 'listed_count': 382,
                                 'location': '',
                                 'name': 'Python Bot',
                                 'notifications': False,
                                 'profile_background_color': '000000',
                                 'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
                                 'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
                                 'profile_background_tile': False,
                                 'profile_banner_url': 'https://pbs.twimg.com/profile_banners/726709023563747328/1504969738',
                                 'profile_image_url': 'http://pbs.twimg.com/profile_images/726714034066706433/5NWdOzpJ_normal.jpg',
                                 'profile_image_url_https': 'https://pbs.twimg.com/profile_images/726714034066706433/5NWdOzpJ_normal.jpg',
                                 'profile_link_color': '1B95E0',
                                 'profile_sidebar_border_color': '000000',
                                 'profile_sidebar_fill_color': '000000',
                                 'profile_text_color': '000000',
                                 'profile_use_background_image': False,
                                 'protected': False,
                                 'screen_name': 'pythonbot_',
                                 'statuses_count': 51771,
                                 'time_zone': 'Pacific Time (US & Canada)',
                                 'translator_type': 'none',
                                 'url': None,
                                 'utc_offset': -25200,
                                 'verified': False}},
 '916053289107640320': {'_id': ObjectId('59e0cbb93842ed0818823535'),
                        'contributors': None,
                        'coordinates': None,
                        'created_at': 'Thu Oct 05 21:31:38 +0000 2017',
                        'entities': {'hashtags': [{'indices': [95, 103],
                                                   'text': 'machine'},
                                                  {'indices': [104, 113],
                                                   'text': 'learning'},
                                                  {'indices': [114, 121],
                                                   'text': 'python'}],
                                     'symbols': [],
                                     'urls': [{'display_url': 'zpy.io/a3fc66fb',
                                               'expanded_url': 'http://zpy.io/a3fc66fb',
                                               'indices': [71, 94],
                                               'url': 'https://t.co/GHzON6itMG'}],
                                     'user_mentions': [{'id': 726709023563747328,
                                                        'id_str': '726709023563747328',
                                                        'indices': [122, 133],
                                                        'name': 'Python Bot',
                                                        'screen_name': 'pythonbot_'}]},
                        'favorite_count': 0,
                        'favorited': False,
                        'geo': None,
                        'id': 916053289107640320,
                        'id_str': '916053289107640320',
                        'in_reply_to_screen_name': None,
                        'in_reply_to_status_id': None,
                        'in_reply_to_status_id_str': None,
                        'in_reply_to_user_id': None,
                        'in_reply_to_user_id_str': None,
                        'is_quote_status': False,
                        'lang': 'es',
                        'metadata': {'iso_language_code': 'es',
                                     'result_type': 'recent'},
                        'place': None,
                        'possibly_sensitive': False,
                        'retweet_count': 1,
                        'retweeted': False,
                        'source': '<a href="https://twitter.com/pythonbot_" '
                                  'rel="nofollow">Python Bot2</a>',
                        'text': 'Python Para Informaticos: Explorando La '
                                'Informacion (spanish Edition)  '
                                'https://t.co/GHzON6itMG #machine #learning '
                                '#python @pythonbot_',
                        'truncated': False,
                        'user': {'contributors_enabled': False,
                                 'created_at': 'Sun May 01 09:45:07 +0000 2016',
                                 'default_profile': False,
                                 'default_profile_image': False,
                                 'description': 'I retweet everything about '
                                                '#Python programming language '
                                                '!',
                                 'entities': {'description': {'urls': []}},
                                 'favourites_count': 0,
                                 'follow_request_sent': False,
                                 'followers_count': 2762,
                                 'following': False,
                                 'friends_count': 2871,
                                 'geo_enabled': False,
                                 'has_extended_profile': False,
                                 'id': 726709023563747328,
                                 'id_str': '726709023563747328',
                                 'is_translation_enabled': False,
                                 'is_translator': False,
                                 'lang': 'en',
                                 'listed_count': 382,
                                 'location': '',
                                 'name': 'Python Bot',
                                 'notifications': False,
                                 'profile_background_color': '000000',
                                 'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
                                 'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
                                 'profile_background_tile': False,
                                 'profile_banner_url': 'https://pbs.twimg.com/profile_banners/726709023563747328/1504969738',
                                 'profile_image_url': 'http://pbs.twimg.com/profile_images/726714034066706433/5NWdOzpJ_normal.jpg',
                                 'profile_image_url_https': 'https://pbs.twimg.com/profile_images/726714034066706433/5NWdOzpJ_normal.jpg',
                                 'profile_link_color': '1B95E0',
                                 'profile_sidebar_border_color': '000000',
                                 'profile_sidebar_fill_color': '000000',
                                 'profile_text_color': '000000',
                                 'profile_use_background_image': False,
                                 'protected': False,
                                 'screen_name': 'pythonbot_',
                                 'statuses_count': 51771,
                                 'time_zone': 'Pacific Time (US & Canada)',
                                 'translator_type': 'none',
                                 'url': None,
                                 'utc_offset': -25200,
                                 'verified': False}},
 '916264384451743744': {'_id': ObjectId('59e0cbb83842ed0818823513'),
                        'contributors': None,
                        'coordinates': None,
                        'created_at': 'Fri Oct 06 11:30:27 +0000 2017',
                        'entities': {'hashtags': [{'indices': [95, 103],
                                                   'text': 'machine'},
                                                  {'indices': [104, 113],
                                                   'text': 'learning'},
                                                  {'indices': [114, 121],
                                                   'text': 'python'}],
                                     'symbols': [],
                                     'urls': [{'display_url': 'zpy.io/a3fc66fb',
                                               'expanded_url': 'http://zpy.io/a3fc66fb',
                                               'indices': [71, 94],
                                               'url': 'https://t.co/GHzON6itMG'}],
                                     'user_mentions': [{'id': 726709023563747328,
                                                        'id_str': '726709023563747328',
                                                        'indices': [122, 133],
                                                        'name': 'Python Bot',
                                                        'screen_name': 'pythonbot_'}]},
                        'favorite_count': 0,
                        'favorited': False,
                        'geo': None,
                        'id': 916264384451743744,
                        'id_str': '916264384451743744',
                        'in_reply_to_screen_name': None,
                        'in_reply_to_status_id': None,
                        'in_reply_to_status_id_str': None,
                        'in_reply_to_user_id': None,
                        'in_reply_to_user_id_str': None,
                        'is_quote_status': False,
                        'lang': 'es',
                        'metadata': {'iso_language_code': 'es',
                                     'result_type': 'recent'},
                        'place': None,
                        'possibly_sensitive': False,
                        'retweet_count': 0,
                        'retweeted': False,
                        'source': '<a href="https://twitter.com/pythonbot_" '
                                  'rel="nofollow">Python Bot2</a>',
                        'text': 'Python Para Informaticos: Explorando La '
                                'Informacion (spanish Edition)  '
                                'https://t.co/GHzON6itMG #machine #learning '
                                '#python @pythonbot_',
                        'truncated': False,
                        'user': {'contributors_enabled': False,
                                 'created_at': 'Sun May 01 09:45:07 +0000 2016',
                                 'default_profile': False,
                                 'default_profile_image': False,
                                 'description': 'I retweet everything about '
                                                '#Python programming language '
                                                '!',
                                 'entities': {'description': {'urls': []}},
                                 'favourites_count': 0,
                                 'follow_request_sent': False,
                                 'followers_count': 2762,
                                 'following': False,
                                 'friends_count': 2871,
                                 'geo_enabled': False,
                                 'has_extended_profile': False,
                                 'id': 726709023563747328,
                                 'id_str': '726709023563747328',
                                 'is_translation_enabled': False,
                                 'is_translator': False,
                                 'lang': 'en',
                                 'listed_count': 382,
                                 'location': '',
                                 'name': 'Python Bot',
                                 'notifications': False,
                                 'profile_background_color': '000000',
                                 'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
                                 'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
                                 'profile_background_tile': False,
                                 'profile_banner_url': 'https://pbs.twimg.com/profile_banners/726709023563747328/1504969738',
                                 'profile_image_url': 'http://pbs.twimg.com/profile_images/726714034066706433/5NWdOzpJ_normal.jpg',
                                 'profile_image_url_https': 'https://pbs.twimg.com/profile_images/726714034066706433/5NWdOzpJ_normal.jpg',
                                 'profile_link_color': '1B95E0',
                                 'profile_sidebar_border_color': '000000',
                                 'profile_sidebar_fill_color': '000000',
                                 'profile_text_color': '000000',
                                 'profile_use_background_image': False,
                                 'protected': False,
                                 'screen_name': 'pythonbot_',
                                 'statuses_count': 51771,
                                 'time_zone': 'Pacific Time (US & Canada)',
                                 'translator_type': 'none',
                                 'url': None,
                                 'utc_offset': -25200,
                                 'verified': False}},
 '916947869067874305': {'_id': ObjectId('59e0cbb53842ed0818823493'),
                        'contributors': None,
                        'coordinates': None,
                        'created_at': 'Sun Oct 08 08:46:22 +0000 2017',
                        'entities': {'hashtags': [{'indices': [95, 103],
                                                   'text': 'machine'},
                                                  {'indices': [104, 113],
                                                   'text': 'learning'},
                                                  {'indices': [114, 121],
                                                   'text': 'python'}],
                                     'symbols': [],
                                     'urls': [{'display_url': 'zpy.io/a3fc66fb',
                                               'expanded_url': 'http://zpy.io/a3fc66fb',
                                               'indices': [71, 94],
                                               'url': 'https://t.co/GHzON6itMG'}],
                                     'user_mentions': [{'id': 726709023563747328,
                                                        'id_str': '726709023563747328',
                                                        'indices': [122, 133],
                                                        'name': 'Python Bot',
                                                        'screen_name': 'pythonbot_'}]},
                        'favorite_count': 1,
                        'favorited': False,
                        'geo': None,
                        'id': 916947869067874305,
                        'id_str': '916947869067874305',
                        'in_reply_to_screen_name': None,
                        'in_reply_to_status_id': None,
                        'in_reply_to_status_id_str': None,
                        'in_reply_to_user_id': None,
                        'in_reply_to_user_id_str': None,
                        'is_quote_status': False,
                        'lang': 'es',
                        'metadata': {'iso_language_code': 'es',
                                     'result_type': 'recent'},
                        'place': None,
                        'possibly_sensitive': False,
                        'retweet_count': 0,
                        'retweeted': False,
                        'source': '<a href="https://twitter.com/pythonbot_" '
                                  'rel="nofollow">Python Bot2</a>',
                        'text': 'Python Para Informaticos: Explorando La '
                                'Informacion (spanish Edition)  '
                                'https://t.co/GHzON6itMG #machine #learning '
                                '#python @pythonbot_',
                        'truncated': False,
                        'user': {'contributors_enabled': False,
                                 'created_at': 'Sun May 01 09:45:07 +0000 2016',
                                 'default_profile': False,
                                 'default_profile_image': False,
                                 'description': 'I retweet everything about '
                                                '#Python programming language '
                                                '!',
                                 'entities': {'description': {'urls': []}},
                                 'favourites_count': 0,
                                 'follow_request_sent': False,
                                 'followers_count': 2762,
                                 'following': False,
                                 'friends_count': 2871,
                                 'geo_enabled': False,
                                 'has_extended_profile': False,
                                 'id': 726709023563747328,
                                 'id_str': '726709023563747328',
                                 'is_translation_enabled': False,
                                 'is_translator': False,
                                 'lang': 'en',
                                 'listed_count': 382,
                                 'location': '',
                                 'name': 'Python Bot',
                                 'notifications': False,
                                 'profile_background_color': '000000',
                                 'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
                                 'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
                                 'profile_background_tile': False,
                                 'profile_banner_url': 'https://pbs.twimg.com/profile_banners/726709023563747328/1504969738',
                                 'profile_image_url': 'http://pbs.twimg.com/profile_images/726714034066706433/5NWdOzpJ_normal.jpg',
                                 'profile_image_url_https': 'https://pbs.twimg.com/profile_images/726714034066706433/5NWdOzpJ_normal.jpg',
                                 'profile_link_color': '1B95E0',
                                 'profile_sidebar_border_color': '000000',
                                 'profile_sidebar_fill_color': '000000',
                                 'profile_text_color': '000000',
                                 'profile_use_background_image': False,
                                 'protected': False,
                                 'screen_name': 'pythonbot_',
                                 'statuses_count': 51771,
                                 'time_zone': 'Pacific Time (US & Canada)',
                                 'translator_type': 'none',
                                 'url': None,
                                 'utc_offset': -25200,
                                 'verified': False}},
 '917849013700964352': {'_id': ObjectId('59e0cbb13842ed08188233f3'),
                        'contributors': None,
                        'coordinates': None,
                        'created_at': 'Tue Oct 10 20:27:12 +0000 2017',
                        'entities': {'hashtags': [{'indices': [95, 103],
                                                   'text': 'machine'},
                                                  {'indices': [104, 113],
                                                   'text': 'learning'},
                                                  {'indices': [114, 121],
                                                   'text': 'python'}],
                                     'symbols': [],
                                     'urls': [{'display_url': 'zpy.io/a3fc66fb',
                                               'expanded_url': 'http://zpy.io/a3fc66fb',
                                               'indices': [71, 94],
                                               'url': 'https://t.co/GHzON6itMG'}],
                                     'user_mentions': [{'id': 726709023563747328,
                                                        'id_str': '726709023563747328',
                                                        'indices': [122, 133],
                                                        'name': 'Python Bot',
                                                        'screen_name': 'pythonbot_'}]},
                        'favorite_count': 2,
                        'favorited': False,
                        'geo': None,
                        'id': 917849013700964352,
                        'id_str': '917849013700964352',
                        'in_reply_to_screen_name': None,
                        'in_reply_to_status_id': None,
                        'in_reply_to_status_id_str': None,
                        'in_reply_to_user_id': None,
                        'in_reply_to_user_id_str': None,
                        'is_quote_status': False,
                        'lang': 'es',
                        'metadata': {'iso_language_code': 'es',
                                     'result_type': 'recent'},
                        'place': None,
                        'possibly_sensitive': False,
                        'retweet_count': 0,
                        'retweeted': False,
                        'source': '<a href="https://twitter.com/pythonbot_" '
                                  'rel="nofollow">Python Bot2</a>',
                        'text': 'Python Para Informaticos: Explorando La '
                                'Informacion (spanish Edition)  '
                                'https://t.co/GHzON6itMG #machine #learning '
                                '#python @pythonbot_',
                        'truncated': False,
                        'user': {'contributors_enabled': False,
                                 'created_at': 'Sun May 01 09:45:07 +0000 2016',
                                 'default_profile': False,
                                 'default_profile_image': False,
                                 'description': 'I retweet everything about '
                                                '#Python programming language '
                                                '!',
                                 'entities': {'description': {'urls': []}},
                                 'favourites_count': 0,
                                 'follow_request_sent': False,
                                 'followers_count': 2762,
                                 'following': False,
                                 'friends_count': 2871,
                                 'geo_enabled': False,
                                 'has_extended_profile': False,
                                 'id': 726709023563747328,
                                 'id_str': '726709023563747328',
                                 'is_translation_enabled': False,
                                 'is_translator': False,
                                 'lang': 'en',
                                 'listed_count': 382,
                                 'location': '',
                                 'name': 'Python Bot',
                                 'notifications': False,
                                 'profile_background_color': '000000',
                                 'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
                                 'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
                                 'profile_background_tile': False,
                                 'profile_banner_url': 'https://pbs.twimg.com/profile_banners/726709023563747328/1504969738',
                                 'profile_image_url': 'http://pbs.twimg.com/profile_images/726714034066706433/5NWdOzpJ_normal.jpg',
                                 'profile_image_url_https': 'https://pbs.twimg.com/profile_images/726714034066706433/5NWdOzpJ_normal.jpg',
                                 'profile_link_color': '1B95E0',
                                 'profile_sidebar_border_color': '000000',
                                 'profile_sidebar_fill_color': '000000',
                                 'profile_text_color': '000000',
                                 'profile_use_background_image': False,
                                 'protected': False,
                                 'screen_name': 'pythonbot_',
                                 'statuses_count': 51771,
                                 'time_zone': 'Pacific Time (US & Canada)',
                                 'translator_type': 'none',
                                 'url': None,
                                 'utc_offset': -25200,
                                 'verified': False}},
 '918026805080182785': {'_id': ObjectId('59e0cbb03842ed08188233d7'),
                        'contributors': None,
                        'coordinates': None,
                        'created_at': 'Wed Oct 11 08:13:41 +0000 2017',
                        'entities': {'hashtags': [{'indices': [90, 106],
                                                   'text': 'MachineLearning'},
                                                  {'indices': [107, 114],
                                                   'text': 'Python'}],
                                     'symbols': [],
                                     'urls': [{'display_url': 'twitter.com/i/web/status/9…',
                                               'expanded_url': 'https://twitter.com/i/web/status/918026805080182785',
                                               'indices': [116, 139],
                                               'url': 'https://t.co/1WuwNRzn8z'}],
                                     'user_mentions': []},
                        'favorite_count': 1,
                        'favorited': False,
                        'geo': None,
                        'id': 918026805080182785,
                        'id_str': '918026805080182785',
                        'in_reply_to_screen_name': None,
                        'in_reply_to_status_id': None,
                        'in_reply_to_status_id_str': None,
                        'in_reply_to_user_id': None,
                        'in_reply_to_user_id_str': None,
                        'is_quote_status': False,
                        'lang': 'es',
                        'metadata': {'iso_language_code': 'es',
                                     'result_type': 'recent'},
                        'place': None,
                        'possibly_sensitive': False,
                        'retweet_count': 0,
                        'retweeted': False,
                        'source': '<a href="http://twitter.com" '
                                  'rel="nofollow">Twitter Web Client</a>',
                        'text': 'Vamos preparando el siguiente libro a '
                                'estudiar que al final la movida me está '
                                'gustando... #MachineLearning #Python… '
                                'https://t.co/1WuwNRzn8z',
                        'truncated': True,
                        'user': {'contributors_enabled': False,
                                 'created_at': 'Sat Dec 12 09:13:46 +0000 2009',
                                 'default_profile': False,
                                 'default_profile_image': False,
                                 'description': 'Me gustan las camisetas y las '
                                                'zapatillas // Desarrollo y '
                                                'Diseño para sistemas Apple // '
                                                'Creador de @GetPomodoroApp · '
                                                '@GetAtentoApp · @MADatBUS · '
                                                '@GetMeteo y...',
                                 'entities': {'description': {'urls': []},
                                              'url': {'urls': [{'display_url': 'desappstre.com',
                                                                'expanded_url': 'http://desappstre.com',
                                                                'indices': [0,
                                                                            23],
                                                                'url': 'https://t.co/oYY42NlHrT'}]}},
                                 'favourites_count': 1512,
                                 'follow_request_sent': False,
                                 'followers_count': 211,
                                 'following': False,
                                 'friends_count': 209,
                                 'geo_enabled': True,
                                 'has_extended_profile': True,
                                 'id': 96309647,
                                 'id_str': '96309647',
                                 'is_translation_enabled': False,
                                 'is_translator': False,
                                 'lang': 'es',
                                 'listed_count': 109,
                                 'location': 'Madrid — Mundo Real™',
                                 'name': 'Adolfo ™',
                                 'notifications': False,
                                 'profile_background_color': '000000',
                                 'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme2/bg.gif',
                                 'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme2/bg.gif',
                                 'profile_background_tile': False,
                                 'profile_banner_url': 'https://pbs.twimg.com/profile_banners/96309647/1501577205',
                                 'profile_image_url': 'http://pbs.twimg.com/profile_images/888396793024794624/O6gHh-lJ_normal.jpg',
                                 'profile_image_url_https': 'https://pbs.twimg.com/profile_images/888396793024794624/O6gHh-lJ_normal.jpg',
                                 'profile_link_color': '1B95E0',
                                 'profile_sidebar_border_color': '000000',
                                 'profile_sidebar_fill_color': '000000',
                                 'profile_text_color': '000000',
                                 'profile_use_background_image': False,
                                 'protected': False,
                                 'screen_name': 'FitoMAD',
                                 'statuses_count': 6893,
                                 'time_zone': 'Madrid',
                                 'translator_type': 'none',
                                 'url': 'https://t.co/oYY42NlHrT',
                                 'utc_offset': 7200,
                                 'verified': False}},
 '918145995736801280': {'_id': ObjectId('59e0cbaf3842ed08188233a4'),
                        'contributors': None,
                        'coordinates': None,
                        'created_at': 'Wed Oct 11 16:07:18 +0000 2017',
                        'entities': {'hashtags': [{'indices': [95, 103],
                                                   'text': 'machine'},
                                                  {'indices': [104, 113],
                                                   'text': 'learning'},
                                                  {'indices': [114, 121],
                                                   'text': 'python'}],
                                     'symbols': [],
                                     'urls': [{'display_url': 'zpy.io/a3fc66fb',
                                               'expanded_url': 'http://zpy.io/a3fc66fb',
                                               'indices': [71, 94],
                                               'url': 'https://t.co/GHzON6itMG'}],
                                     'user_mentions': [{'id': 726709023563747328,
                                                        'id_str': '726709023563747328',
                                                        'indices': [122, 133],
                                                        'name': 'Python Bot',
                                                        'screen_name': 'pythonbot_'}]},
                        'favorite_count': 1,
                        'favorited': False,
                        'geo': None,
                        'id': 918145995736801280,
                        'id_str': '918145995736801280',
                        'in_reply_to_screen_name': None,
                        'in_reply_to_status_id': None,
                        'in_reply_to_status_id_str': None,
                        'in_reply_to_user_id': None,
                        'in_reply_to_user_id_str': None,
                        'is_quote_status': False,
                        'lang': 'es',
                        'metadata': {'iso_language_code': 'es',
                                     'result_type': 'recent'},
                        'place': None,
                        'possibly_sensitive': False,
                        'retweet_count': 0,
                        'retweeted': False,
                        'source': '<a href="https://twitter.com/pythonbot_" '
                                  'rel="nofollow">Python Bot2</a>',
                        'text': 'Python Para Informaticos: Explorando La '
                                'Informacion (spanish Edition)  '
                                'https://t.co/GHzON6itMG #machine #learning '
                                '#python @pythonbot_',
                        'truncated': False,
                        'user': {'contributors_enabled': False,
                                 'created_at': 'Sun May 01 09:45:07 +0000 2016',
                                 'default_profile': False,
                                 'default_profile_image': False,
                                 'description': 'I retweet everything about '
                                                '#Python programming language '
                                                '!',
                                 'entities': {'description': {'urls': []}},
                                 'favourites_count': 0,
                                 'follow_request_sent': False,
                                 'followers_count': 2762,
                                 'following': False,
                                 'friends_count': 2871,
                                 'geo_enabled': False,
                                 'has_extended_profile': False,
                                 'id': 726709023563747328,
                                 'id_str': '726709023563747328',
                                 'is_translation_enabled': False,
                                 'is_translator': False,
                                 'lang': 'en',
                                 'listed_count': 382,
                                 'location': '',
                                 'name': 'Python Bot',
                                 'notifications': False,
                                 'profile_background_color': '000000',
                                 'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
                                 'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
                                 'profile_background_tile': False,
                                 'profile_banner_url': 'https://pbs.twimg.com/profile_banners/726709023563747328/1504969738',
                                 'profile_image_url': 'http://pbs.twimg.com/profile_images/726714034066706433/5NWdOzpJ_normal.jpg',
                                 'profile_image_url_https': 'https://pbs.twimg.com/profile_images/726714034066706433/5NWdOzpJ_normal.jpg',
                                 'profile_link_color': '1B95E0',
                                 'profile_sidebar_border_color': '000000',
                                 'profile_sidebar_fill_color': '000000',
                                 'profile_text_color': '000000',
                                 'profile_use_background_image': False,
                                 'protected': False,
                                 'screen_name': 'pythonbot_',
                                 'statuses_count': 51771,
                                 'time_zone': 'Pacific Time (US & Canada)',
                                 'translator_type': 'none',
                                 'url': None,
                                 'utc_offset': -25200,
                                 'verified': False}},
 '918564356186689536': {'_id': ObjectId('59e0cbad3842ed0818823342'),
                        'contributors': None,
                        'coordinates': None,
                        'created_at': 'Thu Oct 12 19:49:43 +0000 2017',
                        'entities': {'hashtags': [{'indices': [95, 103],
                                                   'text': 'machine'},
                                                  {'indices': [104, 113],
                                                   'text': 'learning'},
                                                  {'indices': [114, 121],
                                                   'text': 'python'}],
                                     'symbols': [],
                                     'urls': [{'display_url': 'zpy.io/a3fc66fb',
                                               'expanded_url': 'http://zpy.io/a3fc66fb',
                                               'indices': [71, 94],
                                               'url': 'https://t.co/GHzON6itMG'}],
                                     'user_mentions': [{'id': 726709023563747328,
                                                        'id_str': '726709023563747328',
                                                        'indices': [122, 133],
                                                        'name': 'Python Bot',
                                                        'screen_name': 'pythonbot_'}]},
                        'favorite_count': 0,
                        'favorited': False,
                        'geo': None,
                        'id': 918564356186689536,
                        'id_str': '918564356186689536',
                        'in_reply_to_screen_name': None,
                        'in_reply_to_status_id': None,
                        'in_reply_to_status_id_str': None,
                        'in_reply_to_user_id': None,
                        'in_reply_to_user_id_str': None,
                        'is_quote_status': False,
                        'lang': 'es',
                        'metadata': {'iso_language_code': 'es',
                                     'result_type': 'recent'},
                        'place': None,
                        'possibly_sensitive': False,
                        'retweet_count': 0,
                        'retweeted': False,
                        'source': '<a href="https://twitter.com/pythonbot_" '
                                  'rel="nofollow">Python Bot2</a>',
                        'text': 'Python Para Informaticos: Explorando La '
                                'Informacion (spanish Edition)  '
                                'https://t.co/GHzON6itMG #machine #learning '
                                '#python @pythonbot_',
                        'truncated': False,
                        'user': {'contributors_enabled': False,
                                 'created_at': 'Sun May 01 09:45:07 +0000 2016',
                                 'default_profile': False,
                                 'default_profile_image': False,
                                 'description': 'I retweet everything about '
                                                '#Python programming language '
                                                '!',
                                 'entities': {'description': {'urls': []}},
                                 'favourites_count': 0,
                                 'follow_request_sent': False,
                                 'followers_count': 2762,
                                 'following': False,
                                 'friends_count': 2871,
                                 'geo_enabled': False,
                                 'has_extended_profile': False,
                                 'id': 726709023563747328,
                                 'id_str': '726709023563747328',
                                 'is_translation_enabled': False,
                                 'is_translator': False,
                                 'lang': 'en',
                                 'listed_count': 382,
                                 'location': '',
                                 'name': 'Python Bot',
                                 'notifications': False,
                                 'profile_background_color': '000000',
                                 'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
                                 'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
                                 'profile_background_tile': False,
                                 'profile_banner_url': 'https://pbs.twimg.com/profile_banners/726709023563747328/1504969738',
                                 'profile_image_url': 'http://pbs.twimg.com/profile_images/726714034066706433/5NWdOzpJ_normal.jpg',
                                 'profile_image_url_https': 'https://pbs.twimg.com/profile_images/726714034066706433/5NWdOzpJ_normal.jpg',
                                 'profile_link_color': '1B95E0',
                                 'profile_sidebar_border_color': '000000',
                                 'profile_sidebar_fill_color': '000000',
                                 'profile_text_color': '000000',
                                 'profile_use_background_image': False,
                                 'protected': False,
                                 'screen_name': 'pythonbot_',
                                 'statuses_count': 51771,
                                 'time_zone': 'Pacific Time (US & Canada)',
                                 'translator_type': 'none',
                                 'url': None,
                                 'utc_offset': -25200,
                                 'verified': False}},
 '918790660802609152': {'_id': ObjectId('59e0cbac3842ed081882331d'),
                        'contributors': None,
                        'coordinates': None,
                        'created_at': 'Fri Oct 13 10:48:58 +0000 2017',
                        'entities': {'hashtags': [{'indices': [95, 103],
                                                   'text': 'machine'},
                                                  {'indices': [104, 113],
                                                   'text': 'learning'},
                                                  {'indices': [114, 121],
                                                   'text': 'python'}],
                                     'symbols': [],
                                     'urls': [{'display_url': 'zpy.io/a3fc66fb',
                                               'expanded_url': 'http://zpy.io/a3fc66fb',
                                               'indices': [71, 94],
                                               'url': 'https://t.co/GHzON6itMG'}],
                                     'user_mentions': [{'id': 726709023563747328,
                                                        'id_str': '726709023563747328',
                                                        'indices': [122, 133],
                                                        'name': 'Python Bot',
                                                        'screen_name': 'pythonbot_'}]},
                        'favorite_count': 0,
                        'favorited': False,
                        'geo': None,
                        'id': 918790660802609152,
                        'id_str': '918790660802609152',
                        'in_reply_to_screen_name': None,
                        'in_reply_to_status_id': None,
                        'in_reply_to_status_id_str': None,
                        'in_reply_to_user_id': None,
                        'in_reply_to_user_id_str': None,
                        'is_quote_status': False,
                        'lang': 'es',
                        'metadata': {'iso_language_code': 'es',
                                     'result_type': 'recent'},
                        'place': None,
                        'possibly_sensitive': False,
                        'retweet_count': 1,
                        'retweeted': False,
                        'source': '<a href="https://twitter.com/pythonbot_" '
                                  'rel="nofollow">Python Bot2</a>',
                        'text': 'Python Para Informaticos: Explorando La '
                                'Informacion (spanish Edition)  '
                                'https://t.co/GHzON6itMG #machine #learning '
                                '#python @pythonbot_',
                        'truncated': False,
                        'user': {'contributors_enabled': False,
                                 'created_at': 'Sun May 01 09:45:07 +0000 2016',
                                 'default_profile': False,
                                 'default_profile_image': False,
                                 'description': 'I retweet everything about '
                                                '#Python programming language '
                                                '!',
                                 'entities': {'description': {'urls': []}},
                                 'favourites_count': 0,
                                 'follow_request_sent': False,
                                 'followers_count': 2762,
                                 'following': False,
                                 'friends_count': 2871,
                                 'geo_enabled': False,
                                 'has_extended_profile': False,
                                 'id': 726709023563747328,
                                 'id_str': '726709023563747328',
                                 'is_translation_enabled': False,
                                 'is_translator': False,
                                 'lang': 'en',
                                 'listed_count': 382,
                                 'location': '',
                                 'name': 'Python Bot',
                                 'notifications': False,
                                 'profile_background_color': '000000',
                                 'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
                                 'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
                                 'profile_background_tile': False,
                                 'profile_banner_url': 'https://pbs.twimg.com/profile_banners/726709023563747328/1504969738',
                                 'profile_image_url': 'http://pbs.twimg.com/profile_images/726714034066706433/5NWdOzpJ_normal.jpg',
                                 'profile_image_url_https': 'https://pbs.twimg.com/profile_images/726714034066706433/5NWdOzpJ_normal.jpg',
                                 'profile_link_color': '1B95E0',
                                 'profile_sidebar_border_color': '000000',
                                 'profile_sidebar_fill_color': '000000',
                                 'profile_text_color': '000000',
                                 'profile_use_background_image': False,
                                 'protected': False,
                                 'screen_name': 'pythonbot_',
                                 'statuses_count': 51771,
                                 'time_zone': 'Pacific Time (US & Canada)',
                                 'translator_type': 'none',
                                 'url': None,
                                 'utc_offset': -25200,
                                 'verified': False}},
 '918790742461550592': {'_id': ObjectId('59e0cbac3842ed081882331c'),
                        'contributors': None,
                        'coordinates': None,
                        'created_at': 'Fri Oct 13 10:49:17 +0000 2017',
                        'entities': {'hashtags': [{'indices': [111, 119],
                                                   'text': 'machine'},
                                                  {'indices': [120, 129],
                                                   'text': 'learning'},
                                                  {'indices': [130, 137],
                                                   'text': 'python'}],
                                     'symbols': [],
                                     'urls': [{'display_url': 'zpy.io/a3fc66fb',
                                               'expanded_url': 'http://zpy.io/a3fc66fb',
                                               'indices': [87, 110],
                                               'url': 'https://t.co/GHzON6itMG'}],
                                     'user_mentions': [{'id': 726709023563747328,
                                                        'id_str': '726709023563747328',
                                                        'indices': [3, 14],
                                                        'name': 'Python Bot',
                                                        'screen_name': 'pythonbot_'}]},
                        'favorite_count': 0,
                        'favorited': False,
                        'geo': None,
                        'id': 918790742461550592,
                        'id_str': '918790742461550592',
                        'in_reply_to_screen_name': None,
                        'in_reply_to_status_id': None,
                        'in_reply_to_status_id_str': None,
                        'in_reply_to_user_id': None,
                        'in_reply_to_user_id_str': None,
                        'is_quote_status': False,
                        'lang': 'es',
                        'metadata': {'iso_language_code': 'es',
                                     'result_type': 'recent'},
                        'place': None,
                        'possibly_sensitive': False,
                        'retweet_count': 1,
                        'retweeted': False,
                        'retweeted_status': {'contributors': None,
                                             'coordinates': None,
                                             'created_at': 'Fri Oct 13 '
                                                           '10:48:58 +0000 '
                                                           '2017',
                                             'entities': {'hashtags': [{'indices': [95,
                                                                                    103],
                                                                        'text': 'machine'},
                                                                       {'indices': [104,
                                                                                    113],
                                                                        'text': 'learning'},
                                                                       {'indices': [114,
                                                                                    121],
                                                                        'text': 'python'}],
                                                          'symbols': [],
                                                          'urls': [{'display_url': 'zpy.io/a3fc66fb',
                                                                    'expanded_url': 'http://zpy.io/a3fc66fb',
                                                                    'indices': [71,
                                                                                94],
                                                                    'url': 'https://t.co/GHzON6itMG'}],
                                                          'user_mentions': [{'id': 726709023563747328,
                                                                             'id_str': '726709023563747328',
                                                                             'indices': [122,
                                                                                         133],
                                                                             'name': 'Python '
                                                                                     'Bot',
                                                                             'screen_name': 'pythonbot_'}]},
                                             'favorite_count': 0,
                                             'favorited': False,
                                             'geo': None,
                                             'id': 918790660802609152,
                                             'id_str': '918790660802609152',
                                             'in_reply_to_screen_name': None,
                                             'in_reply_to_status_id': None,
                                             'in_reply_to_status_id_str': None,
                                             'in_reply_to_user_id': None,
                                             'in_reply_to_user_id_str': None,
                                             'is_quote_status': False,
                                             'lang': 'es',
                                             'metadata': {'iso_language_code': 'es',
                                                          'result_type': 'recent'},
                                             'place': None,
                                             'possibly_sensitive': False,
                                             'retweet_count': 1,
                                             'retweeted': False,
                                             'source': '<a '
                                                       'href="https://twitter.com/pythonbot_" '
                                                       'rel="nofollow">Python '
                                                       'Bot2</a>',
                                             'text': 'Python Para '
                                                     'Informaticos: Explorando '
                                                     'La Informacion (spanish '
                                                     'Edition)  '
                                                     'https://t.co/GHzON6itMG '
                                                     '#machine #learning '
                                                     '#python @pythonbot_',
                                             'truncated': False,
                                             'user': {'contributors_enabled': False,
                                                      'created_at': 'Sun May '
                                                                    '01 '
                                                                    '09:45:07 '
                                                                    '+0000 '
                                                                    '2016',
                                                      'default_profile': False,
                                                      'default_profile_image': False,
                                                      'description': 'I '
                                                                     'retweet '
                                                                     'everything '
                                                                     'about '
                                                                     '#Python '
                                                                     'programming '
                                                                     'language '
                                                                     '!',
                                                      'entities': {'description': {'urls': []}},
                                                      'favourites_count': 0,
                                                      'follow_request_sent': False,
                                                      'followers_count': 2762,
                                                      'following': False,
                                                      'friends_count': 2871,
                                                      'geo_enabled': False,
                                                      'has_extended_profile': False,
                                                      'id': 726709023563747328,
                                                      'id_str': '726709023563747328',
                                                      'is_translation_enabled': False,
                                                      'is_translator': False,
                                                      'lang': 'en',
                                                      'listed_count': 382,
                                                      'location': '',
                                                      'name': 'Python Bot',
                                                      'notifications': False,
                                                      'profile_background_color': '000000',
                                                      'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
                                                      'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
                                                      'profile_background_tile': False,
                                                      'profile_banner_url': 'https://pbs.twimg.com/profile_banners/726709023563747328/1504969738',
                                                      'profile_image_url': 'http://pbs.twimg.com/profile_images/726714034066706433/5NWdOzpJ_normal.jpg',
                                                      'profile_image_url_https': 'https://pbs.twimg.com/profile_images/726714034066706433/5NWdOzpJ_normal.jpg',
                                                      'profile_link_color': '1B95E0',
                                                      'profile_sidebar_border_color': '000000',
                                                      'profile_sidebar_fill_color': '000000',
                                                      'profile_text_color': '000000',
                                                      'profile_use_background_image': False,
                                                      'protected': False,
                                                      'screen_name': 'pythonbot_',
                                                      'statuses_count': 51771,
                                                      'time_zone': 'Pacific '
                                                                   'Time (US & '
                                                                   'Canada)',
                                                      'translator_type': 'none',
                                                      'url': None,
                                                      'utc_offset': -25200,
                                                      'verified': False}},
                        'source': '<a href="http://www.breadfruithead.com" '
                                  'rel="nofollow">breadfruithead</a>',
                        'text': 'RT @pythonbot_: Python Para Informaticos: '
                                'Explorando La Informacion (spanish Edition)  '
                                'https://t.co/GHzON6itMG #machine #learning '
                                '#python @…',
                        'truncated': False,
                        'user': {'contributors_enabled': False,
                                 'created_at': 'Tue Nov 20 04:42:41 +0000 2007',
                                 'default_profile': False,
                                 'default_profile_image': False,
                                 'description': 'After studying computer '
                                                'science, I worked as a '
                                                'graphic designer and a web '
                                                'developer. Now, I am addicted '
                                                'to FP. Deeplearning, RX.js,  '
                                                'Tensorflow and IoT.',
                                 'entities': {'description': {'urls': []}},
                                 'favourites_count': 53,
                                 'follow_request_sent': False,
                                 'followers_count': 1099,
                                 'following': False,
                                 'friends_count': 826,
                                 'geo_enabled': True,
                                 'has_extended_profile': False,
                                 'id': 10403102,
                                 'id_str': '10403102',
                                 'is_translation_enabled': False,
                                 'is_translator': False,
                                 'lang': 'en',
                                 'listed_count': 82,
                                 'location': 'ON, Canada',
                                 'name': 'Roydell Clarke',
                                 'notifications': False,
                                 'profile_background_color': '000000',
                                 'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme18/bg.gif',
                                 'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme18/bg.gif',
                                 'profile_background_tile': False,
                                 'profile_banner_url': 'https://pbs.twimg.com/profile_banners/10403102/1487785423',
                                 'profile_image_url': 'http://pbs.twimg.com/profile_images/834449190575026176/7Wj1bSdK_normal.jpg',
                                 'profile_image_url_https': 'https://pbs.twimg.com/profile_images/834449190575026176/7Wj1bSdK_normal.jpg',
                                 'profile_link_color': '9266CC',
                                 'profile_sidebar_border_color': '000000',
                                 'profile_sidebar_fill_color': '000000',
                                 'profile_text_color': '000000',
                                 'profile_use_background_image': False,
                                 'protected': False,
                                 'screen_name': 'Roydell_Clarke',
                                 'statuses_count': 18705,
                                 'time_zone': 'Eastern Time (US & Canada)',
                                 'translator_type': 'none',
                                 'url': None,
                                 'utc_offset': -14400,
                                 'verified': False}}}
